[package]
title = "Motion Extension"
version = "0.0.1"
category = "Robotics"

[dependencies]
"omni.usd" = {}
"omni.client" = {}
"omni.timeline" = {}
"isaacsim.replicator.agent" = {}
"isaacsim.replicator.writers" = {}

[[python.module]]
name = "motion.extension"
