services:
  server:
    image: python:3.12-slim
    container_name: ${SCOPE:-motion}-server
    restart: unless-stopped
    network_mode: bridge
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - storage:/storage
    command: ["/bin/sh", "-lc", "apt -y -qq update && apt -y -qq install curl && pip install -r server/requirements.txt && pip install -e . && uvicorn server.server:app --host 0.0.0.0 --port 8080"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8080/health > /dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 120s
  react:
    image: node:alpine
    container_name: ${SCOPE:-motion}-react
    restart: unless-stopped
    depends_on:
      - server
    network_mode: "service:server"
    working_dir: /app/react
    volumes:
      - ${PWD}:/app
    command: ["/bin/sh", "-lc", "npm ci --no-audit --no-fund && npm run dev -- --host"]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:5173 > /dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 120s
  nats:
    image: nats:alpine
    container_name: ${SCOPE:-motion}-nats
    restart: unless-stopped
    depends_on:
      - server
    network_mode: "service:server"
    command: ["-a", "127.0.0.1", "-m", "8222", "-js", "-sd", "/storage/nats"]
    volumes:
      - storage:/storage
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8222/healthz >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
  minio:
    image: minio/minio:latest
    container_name: ${SCOPE:-motion}-minio
    restart: unless-stopped
    depends_on:
      - server
    network_mode: "service:server"
    volumes:
      - storage:/storage
    environment:
      MINIO_ROOT_USER: username
      MINIO_ROOT_PASSWORD: password
      MINIO_REGION: us-east-1
    command: ["server", "/storage/minio"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:9000/minio/health/ready >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  worker:
    image: python:3.12-slim
    container_name: ${SCOPE:-motion}-worker
    restart: unless-stopped
    depends_on:
      - server
    network_mode: "service:server"
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - storage:/storage
      - /etc/machine-id:/etc/machine-id:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MOTION=${PWD}
      - SCOPE=${SCOPE}
    command: ["/bin/sh", "-lc", "apt -y -qq update && apt -y -qq install docker-cli docker-compose curl && pip install -r server/requirements.txt && pip install -e . && python -m server.worker"]
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:9999/health >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 120s
  node-ros2:
    image: python:3.12-slim
    container_name: ${SCOPE:-motion}-node-ros2
    restart: no
    depends_on:
      - server
    network_mode: "service:server"
    working_dir: /app
    volumes:
      - ${MOTION:-$PWD}:/app:ro
      - storage:/storage:ro
    environment:
      - SCOPE=${SCOPE}
    entrypoint: ["/bin/bash"]
    command: ["-lc", "apt -y -qq update && apt -y -qq install curl && pip install aiohttp nats-py boto3 && python -m server.node"]
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:8888/health >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 120s
    profiles: ["node"]
  node-isaac:
    image: nvcr.io/nvidia/isaac-sim:5.0.0
    container_name: ${SCOPE:-motion}-node-isaac
    restart: no
    depends_on:
      - server
    network_mode: "service:server"
    working_dir: /app
    volumes:
      - ${MOTION:-$PWD}/server/extension:/isaac-sim/exts/motion.extension:ro
      - ${MOTION:-$PWD}:/app:ro
      - storage:/storage:ro
    environment:
      - SCOPE=${SCOPE}
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
    entrypoint: ["/bin/bash"]
    command: ["-lc", "sleep infinity"]
    profiles: ["node"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  storage: {}
