services:
  nats:
    image: nats:alpine
    container_name: ${SCOPE:-motion}-nats
    restart: unless-stopped
    network_mode: bridge
    command: ["-a", "127.0.0.1", "-m", "8222", "-js", "-sd", "/storage/nats"]
    volumes:
      - shared-storage:/storage
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8222/healthz >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
  minio:
    image: minio/minio:latest
    container_name: ${SCOPE:-motion}-minio
    restart: unless-stopped
    depends_on:
      - nats
    network_mode: "service:nats"
    volumes:
      - shared-storage:/storage
    environment:
      MINIO_ROOT_USER: username
      MINIO_ROOT_PASSWORD: password
      MINIO_REGION: us-east-1
    command: ["server", "/storage/minio"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:9000/minio/health/ready >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  worker:
    image: python:3.12-slim
    container_name: ${SCOPE:-motion}-worker
    restart: unless-stopped
    depends_on:
      - nats
      - minio
    network_mode: "service:nats"
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - shared-storage:/storage
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["/bin/sh", "-lc", "apt -y -qq update && apt -y -qq install docker.io curl && pip install -r server/requirements.txt && pip install -e . && python -m server.worker"]
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:9999/health >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 120s
  server:
    image: python:3.12-slim
    container_name: ${SCOPE:-motion}-server
    restart: unless-stopped
    depends_on:
      - worker
    network_mode: "service:nats"
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - shared-storage:/storage
    command: ["/bin/sh", "-lc", "apt -y -qq update && apt -y -qq install curl && pip install -r server/requirements.txt && pip install -e . && uvicorn server.server:app --host 0.0.0.0 --port 8080"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8080/health > /dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 120s
  react:
    image: node:alpine
    container_name: ${SCOPE:-motion}-react
    restart: unless-stopped
    depends_on:
      - server
    network_mode: "service:nats"
    working_dir: /app/react
    volumes:
      - ${PWD}:/app
    command: ["/bin/sh", "-lc", "npm ci --no-audit --no-fund && npm run dev -- --host"]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:5173 > /dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 120s
volumes:
  shared-storage: {}
